spring:
 application:
  name: e-commerce
 jpa:
  database: mysql
  show-sql: true
  hibernate:
   ddl-auto: update
 datasource:
  url: jdbc:mysql://localhost:3308/e-commerce
  username: root
  password: supersecret
  driverClassName: com.mysql.cj.jdbc.Driver
 servlet:
   multipart:
    enabled: true         # Active le multipart
    max-file-size: 10MB    # Taille max du fichier
    max-request-size: 10MB # Taille max de la requête multipart
jwt:
   secret: remplacezparvotreclebase64generee  # Remplacez par votre clé publique en base64
   expiration: 1200  # Durée d'expiration en secondes (20 minutes)
