spring:
 application:
  name: e-commerce
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  database-platform: org.hibernate.dialect.H2Dialect
 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: root
  password: password
 h2:
  console:
   enabled: true
 servlet:
   multipart:
    enabled: true         # Active le multipart
    max-file-size: 10MB    # Taille max du fichier
    max-request-size: 10MB # Taille max de la requête multipart
jwt:
   secret: remplacezparvotreclebase64generee
   expiration: 1200  # Durée d'expiration en secondes (20 minutes)
