spring:
 application:
  name: e-commerce
 jpa:
  database: mysql
  show-sql: true
  hibernate:
   ddl-auto: update
 datasource:
  url: jdbc:mysql://localhost:3308/e-commerce
  username: root
  password: supersecret
  driverClassName: com.mysql.cj.jdbc.Driver
jwt:
  secret: your_secret_key
  expiration: 3600
stripe:
  api:
    key: sk_test_51PVFTHP8RWx0diMWWy8IRbANSx1rbWqu2pWAcYbH5LrJRSL8A7WB5yZzAVMPVmk0TgJJKvWfMb1xDzdF1i9sArJ3006AeBqas9
