spring:
 application:
  name: e-commerce
 jpa:
  database: mysql
  show-sql: true
  hibernate:
   ddl-auto: update
 datasource:
  url: jdbc:mysql://localhost:3308/e-commerce
  username: root
  password: supersecret
  driverClassName: com.mysql.cj.jdbc.Driver
jwt:
  secret: your_secret_key
  expiration: 3600
mail:
  host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true